### ISSUE TITLE
谁知道这工程android studio最低啥版本？

### ISSUE THREAD

**Issue by salmanit** [rengwuxian/WeCompose#3]
我下了个4.2beta4也不行，必须是右边的canary版吗？

![image](https://user-images.githubusercontent.com/6285702/108799116-73b4bb80-75ca-11eb-868a-9581250a45c6.png)

**Comment by JankingWon** [comment]
是的，需要预览版才可以用compose

**Comment by rengwuxian** [comment]
是，Canary 才可以

**Comment by salmanit** [comment]
好的，谢谢，等我下个新的再测试
