### ISSUE TITLE
ChatPage的列表不能正确显示长列表

### ISSUE THREAD

**Issue by re-ovo** [rengwuxian/WeCompose#4]
如图:
![image](https://user-images.githubusercontent.com/21152113/109383176-c15d5b00-791f-11eb-9e62-42921334194d.png)

下面任然是有一行聊天记录的，但是被底部导航栏遮挡了，我写了个简单的测试:
![image](https://user-images.githubusercontent.com/21152113/109383192-e6ea6480-791f-11eb-8d20-92c49205e1df.png)

可以看到list跑到导航栏下面去了，该怎么解决这个问题呢？还是这是compose的bug?

**Comment by mofada** [comment]
你把代码发下看看

**Comment by re-ovo** [comment]
> 你把代码发下看看

用这个项目就能复现啊，多添加些聊天记录就行

**Comment by mofada** [comment]
![image](https://user-images.githubusercontent.com/22286246/109425447-39f91000-7a23-11eb-8702-a522d9168df5.png)

**Comment by jiangdashao** [comment]
用手势的话是正常的，但是如果用虚拟导航栏是不正常的

**Comment by re-ovo** [comment]
你是默认下载的代码没有改过吗？我重新下载试了下还是这样

**Comment by mofada** [comment]
我是跟着视频做的, 这里用的 `Column` 组件, 你用的是 `Scaffold` ?

**Comment by re-ovo** [comment]
是的，我完完全全下载的他的代码，Column应该是没有问题的，我怀疑可能是Scaffold的问题

**Comment by mofada** [comment]
确实有这个问题, `Scaffold`控件中, 如果加了`bottomBar`,那么`body`就会被`bottomBar`挡住

**Comment by mofada** [comment]
![image](https://user-images.githubusercontent.com/22286246/109441994-da762100-7a71-11eb-894c-0ce2f160ebb2.png)

**Comment by mofada** [comment]
@rengwuxian 朱老师, 你看下这个问题

**Comment by mofada** [comment]
@rengwuxian 
在`Scaffold.kt:313`行 ,
```
val bodyContentHeight = layoutHeight - topBarHeight
```
是不是因为这里没有减`bottomBarHeight`啊?

**Comment by rengwuxian** [comment]
https://github.com/rengwuxian/WeCompose/commit/64709c94481344c37816deb2628c0ac066be3d45 已修复，感谢大佬反馈！

**Comment by rengwuxian** [comment]
修复方式：给 `content` 加上传入的 `paddingValues` 参数，这个参数自带 `bottomBar` 的高度。
