### ISSUE TITLE
老师，似乎有个小问题

### ISSUE THREAD

**Issue by rin0chan** [rengwuxian/WeCompose#5]
这种盖住的方法，如果点到主界面有 clickable 属性的控件似乎会触发，比如

![image](https://user-images.githubusercontent.com/31311826/111661680-83ad6d00-880f-11eb-8ad5-e572adb71d4e.png)
![image](https://user-images.githubusercontent.com/31311826/111661699-89a34e00-880f-11eb-9c94-e4c690c2ff81.png)
![image](https://user-images.githubusercontent.com/31311826/111662300-15b57580-8810-11eb-8d4a-ec40c38058c5.png)

在聊天详情页点击这个，再退出来会发现已经触发了，如果聊天详情的 TopAppBar 没有设置主题按钮的话，点击右上角也是会触发主界面的主题按钮变色的

我在写自己的软件的时候发现了这个问题，然后我写了判断是不是不在主界面的 mutableStateOf 可以解决

但是如果像聊天页这种次级页面有很多的话，靠设置 mutableStateOf 来控制主页面所有可触发 clickable 的控件在非主页面的时候不触发是不是有点麻烦？(如果 clickable 属性的控件很多的话

**Comment by re-ovo** [comment]
@Nthily 推荐用官方navigation库实现多页面: https://developer.android.com/jetpack/compose/navigation?hl=zh-cn
